version: '2'

services:
  frontend:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - 8080:8080
    links:
      - server
      - mysql
    volumes:
      - ./.babelrc:/usr/src/app/.babelrc
      - ./.postcssrc.js:/usr/src/app/.postcssrc.js
      - ./package.json:/usr/src/app/package.json
      - ./build:/usr/src/app/build
      - ./config:/usr/src/app/config
      - ./src:/usr/src/app/src
      - ./static:/usr/src/app/static
      - ./test:/usr/src/app/test
    command: npm start
    environment:
      - API_HOST=server

  server:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - 8000:8000
    volumes:
      - ./.sequelizerc:/usr/src/app/.sequelizerc
      - ./package.json:/usr/src/app/package.json
      - ./index.js:/usr/src/app/index.js
      - ./server:/usr/src/app/server
      - ./static:/usr/src/app/static
      - ./test:/usr/src/app/test
      - ./static/uploads:/uploads
    environment:
      - NODE_ENV=development
      - PORT=
      - DB_HOST=mysql
      - DB_NAME=cie
      - DB_USER=cie_user
      - DB_PASSWORD=password

  mysql:
    image: mysql:5.7.18
    ports:
      - 33060:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cie
      - MYSQL_USER=cie_user
      - MYSQL_PASSWORD=password

volumes:
  mysql_data:
