version: '2'

services:
  frontend:
    image: node:6.11.1
    ports:
      - 8080:8080
    links:
      - server
    volumes:
        - .:/user/src/app
    working_dir: /user/src/app
    command: >
      bash -c "npm rebuild node-sass &&
               npm start"
    environment:
      - NODE_ENV=development
      - API_HOST=server
  server:
    image: node:6.11.1
    ports:
      - 8000:8000
    volumes:
      - .:/user/src/app
    working_dir: /user/src/app
    command: ["npm", "run", "dev:server"]
    environment:
      - NODE_ENV=development
      - PORT=8000
